[package]
name = "speechserverdaemon"
version = "0.1.0"
edition = "2021"
authors = ["StarTuz <startuz@example.com>"]
description = "A modern, secure, next-generation speech server for Linux written in Rust."
license = "MIT"
repository = "https://github.com/StarTuz/speechd-ng"

[dependencies]
config = "0.15.19"
cpal = "0.17.0"
hound = "3.5.1"
lazy_static = "1.5.0"
reqwest = { version = "0.12.28", features = ["json", "blocking"] }
ringbuf = "0.4.9"
rodio = "0.17.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
dirs = "6.0.0"
tokio = { version = "1.48.0", features = ["full"] }
wait-timeout = "0.2.1"
zbus = { version = "5.12.0", features = ["tokio"] }
